const mongoose = require("mongoose");
const Job = require("./models/Job");

// Same DB path as server.js
const DB_PATH =
  "mongodb://prachi:root80772@ac-dc5i5to-shard-00-00.ypuy1wc.mongodb.net:27017,ac-dc5i5to-shard-00-01.ypuy1wc.mongodb.net:27017,ac-dc5i5to-shard-00-02.ypuy1wc.mongodb.net:27017/job-portal?ssl=true&replicaSet=atlas-tjgphf-shard-0&authSource=admin&appName=prachidb";

// Recruiter ID
const recruiterId = "6a5b0643b31e554d7dbfac3f";

const jobs = [
  {
  title: "Frontend Engineer",
  companyName: "PhonePe",
  description: "Develop responsive web applications using React, optimize UI performance, collaborate with backend teams, and write reusable components for scalable products.",
  location: "Bangalore",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "React, JavaScript, CSS, HTML",
  postedBy: recruiterId,
},
{
  title: "Backend Engineer",
  companyName: "Razorpay",
  description: "Build secure REST APIs, integrate payment services, optimize MongoDB queries, and ensure scalable backend architecture.",
  location: "Bangalore",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "Node.js, Express, MongoDB",
  postedBy: recruiterId,
},
{
  title: "Software Developer",
  companyName: "Freshworks",
  description: "Design and develop enterprise software, fix bugs, improve application performance, and participate in code reviews.",
  location: "Chennai",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "JavaScript, Git, REST API",
  postedBy: recruiterId,
},
{
  title: "MERN Stack Developer",
  companyName: "Mindtree",
  description: "Develop full-stack applications using MongoDB, Express, React, and Node.js while following industry best practices.",
  location: "Pune",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "MongoDB, Express, React, Node.js",
  postedBy: recruiterId,
},
{
  title: "Software Tester",
  companyName: "LTIMindtree",
  description: "Execute test cases, identify software defects, automate testing processes, and ensure high product quality.",
  location: "Hyderabad",
  salary: "₹6 LPA",
  jobType: "Full Time",
  skilledRequired: "Selenium, Manual Testing, Java",
  postedBy: recruiterId,
},
{
  title: "Cloud Support Engineer",
  companyName: "AWS",
  description: "Support cloud infrastructure, troubleshoot deployment issues, monitor systems, and improve application reliability.",
  location: "Hyderabad",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "AWS, Linux, Networking",
  postedBy: recruiterId,
},
{
  title: "Android Engineer",
  companyName: "Samsung",
  description: "Develop Android applications, optimize performance, integrate APIs, and collaborate with cross-functional teams.",
  location: "Noida",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "Kotlin, Android SDK",
  postedBy: recruiterId,
},
{
  title: "iOS Engineer",
  companyName: "Apple India",
  description: "Build and maintain iOS applications, optimize user experience, and implement new mobile features.",
  location: "Bangalore",
  salary: "₹15 LPA",
  jobType: "Full Time",
  skilledRequired: "Swift, UIKit, Xcode",
  postedBy: recruiterId,
},
{
  title: "SQL Developer",
  companyName: "Infosys",
  description: "Write optimized SQL queries, maintain databases, generate reports, and improve database performance.",
  location: "Mysore",
  salary: "₹7 LPA",
  jobType: "Full Time",
  skilledRequired: "SQL, MySQL, Oracle",
  postedBy: recruiterId,
},
{
  title: "Automation Engineer",
  companyName: "Cognizant",
  description: "Develop automation scripts, execute regression testing, and improve software delivery quality.",
  location: "Kolkata",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "Selenium, TestNG, Java",
  postedBy: recruiterId,
},
{
  title: "Big Data Engineer",
  companyName: "Cloudera",
  description: "Build big data pipelines, process large datasets, and optimize distributed data systems.",
  location: "Bangalore",
  salary: "₹14 LPA",
  jobType: "Full Time",
  skilledRequired: "Hadoop, Spark, Hive",
  postedBy: recruiterId,
},
{
  title: "Data Visualization Analyst",
  companyName: "EY",
  description: "Create dashboards and visual reports to help business teams make informed decisions using data insights.",
  location: "Delhi",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "Power BI, Tableau, SQL",
  postedBy: recruiterId,
},
{
  title: "Network Administrator",
  companyName: "Juniper Networks",
  description: "Maintain enterprise network infrastructure, troubleshoot connectivity issues, and ensure network security.",
  location: "Mumbai",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "CCNA, Firewall, Routing",
  postedBy: recruiterId,
},
{
  title: "Security Consultant",
  companyName: "KPMG",
  description: "Assess security risks, conduct audits, recommend security improvements, and support compliance initiatives.",
  location: "Gurgaon",
  salary: "₹13 LPA",
  jobType: "Full Time",
  skilledRequired: "Cyber Security, Risk Assessment",
  postedBy: recruiterId,
},
{
  title: "PHP Full Stack Developer",
  companyName: "Net Solutions",
  description: "Develop full-stack web applications using Laravel, MySQL, JavaScript, and Bootstrap.",
  location: "Chandigarh",
  salary: "₹7 LPA",
  jobType: "Full Time",
  skilledRequired: "PHP, Laravel, MySQL",
  postedBy: recruiterId,
},
{
  title: "WordPress Developer",
  companyName: "Webkul",
  description: "Develop custom WordPress themes and plugins, optimize website performance, and maintain client websites.",
  location: "Noida",
  salary: "₹6 LPA",
  jobType: "Full Time",
  skilledRequired: "WordPress, PHP, CSS",
  postedBy: recruiterId,
},
{
  title: "Python Data Analyst",
  companyName: "Mu Sigma",
  description: "Analyze business datasets using Python, create reports, and support strategic decision-making.",
  location: "Bangalore",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "Python, Pandas, SQL",
  postedBy: recruiterId,
},
{
  title: "AI Research Engineer",
  companyName: "NVIDIA",
  description: "Research AI models, optimize deep learning algorithms, and deploy intelligent software solutions.",
  location: "Pune",
  salary: "₹20 LPA",
  jobType: "Full Time",
  skilledRequired: "Python, PyTorch, Deep Learning",
  postedBy: recruiterId,
},{
  title: "Web Developer",
  companyName: "Oracle",
  description: "Develop responsive websites and integrate backend APIs.",
  location: "Bangalore",
  salary: "₹7 LPA",
  jobType: "Full Time",
  skilledRequired: "HTML, CSS, JavaScript, React",
  postedBy: recruiterId,
},
{
  title: "Software Architect",
  companyName: "IBM",
  description: "Design scalable software architecture and guide development teams.",
  location: "Pune",
  salary: "₹22 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, Microservices, AWS",
  postedBy: recruiterId,
},
{
  title: "API Developer",
  companyName: "PayU",
  description: "Develop secure REST APIs and payment integrations.",
  location: "Gurgaon",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "Node.js, Express, REST API",
  postedBy: recruiterId,
},
{
  title: "Go Developer",
  companyName: "Swiggy",
  description: "Build high-performance backend services using Golang.",
  location: "Bangalore",
  salary: "₹16 LPA",
  jobType: "Full Time",
  skilledRequired: "Go, Docker, PostgreSQL",
  postedBy: recruiterId,
},
{
  title: "Rust Developer",
  companyName: "CoinSwitch",
  description: "Develop secure backend systems using Rust.",
  location: "Bangalore",
  salary: "₹18 LPA",
  jobType: "Full Time",
  skilledRequired: "Rust, Linux, Git",
  postedBy: recruiterId,
},
{
  title: "C++ Developer",
  companyName: "Siemens",
  description: "Develop high-performance desktop and embedded applications.",
  location: "Pune",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "C++, STL, OOP",
  postedBy: recruiterId,
},
{
  title: "C# Developer",
  companyName: "Infosys",
  description: "Develop enterprise applications using .NET technologies.",
  location: "Hyderabad",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "C#, .NET, SQL Server",
  postedBy: recruiterId,
},
{
  title: ".NET Developer",
  companyName: "LTIMindtree",
  description: "Build scalable business applications using ASP.NET.",
  location: "Mumbai",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "ASP.NET, C#, SQL",
  postedBy: recruiterId,
},
{
  title: "Laravel Developer",
  companyName: "Webkul",
  description: "Develop secure PHP web applications using Laravel.",
  location: "Noida",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "Laravel, PHP, MySQL",
  postedBy: recruiterId,
},
{
  title: "Django Developer",
  companyName: "Tata Elxsi",
  description: "Develop backend systems using Django framework.",
  location: "Bangalore",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "Python, Django, PostgreSQL",
  postedBy: recruiterId,
},
{
  title: "Vue.js Developer",
  companyName: "BrowserStack",
  description: "Build modern frontend applications using Vue.js.",
  location: "Mumbai",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "Vue.js, JavaScript",
  postedBy: recruiterId,
},
{
  title: "SRE Engineer",
  companyName: "Google",
  description: "Maintain production reliability and automate operations.",
  location: "Hyderabad",
  salary: "₹20 LPA",
  jobType: "Full Time",
  skilledRequired: "Linux, Kubernetes, Monitoring",
  postedBy: recruiterId,
},
{
  title: "Platform Engineer",
  companyName: "Adobe",
  description: "Develop internal engineering platforms and deployment tools.",
  location: "Noida",
  salary: "₹15 LPA",
  jobType: "Full Time",
  skilledRequired: "Docker, Kubernetes, AWS",
  postedBy: recruiterId,
},
{
  title: "Release Engineer",
  companyName: "SAP",
  description: "Manage software releases and deployment pipelines.",
  location: "Bangalore",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "Git, Jenkins, CI/CD",
  postedBy: recruiterId,
},
{
  title: "Build Engineer",
  companyName: "Intel",
  description: "Maintain automated build systems and release workflows.",
  location: "Bangalore",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "Gradle, Maven, Git",
  postedBy: recruiterId,
},
{
  title: "Computer Vision Engineer",
  companyName: "NVIDIA",
  description: "Develop image processing and computer vision solutions.",
  location: "Pune",
  salary: "₹18 LPA",
  jobType: "Full Time",
  skilledRequired: "OpenCV, Python, Deep Learning",
  postedBy: recruiterId,
},
{
  title: "NLP Engineer",
  companyName: "OpenAI India",
  description: "Build natural language processing applications.",
  location: "Bangalore",
  salary: "₹19 LPA",
  jobType: "Full Time",
  skilledRequired: "Python, NLP, Transformers",
  postedBy: recruiterId,
},
{
  title: "Prompt Engineer",
  companyName: "Anthropic India",
  description: "Design and evaluate prompts for AI applications.",
  location: "Remote",
  salary: "₹17 LPA",
  jobType: "Remote",
  skilledRequired: "LLMs, Prompt Engineering, Python",
  postedBy: recruiterId,
},
{
  title: "Data Warehouse Engineer",
  companyName: "Snowflake",
  description: "Build and maintain enterprise data warehouses.",
  location: "Hyderabad",
  salary: "₹13 LPA",
  jobType: "Full Time",
  skilledRequired: "Snowflake, SQL, ETL",
  postedBy: recruiterId,
},
{
  title: "ETL Developer",
  companyName: "Informatica",
  description: "Develop ETL pipelines for enterprise data systems.",
  location: "Chennai",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "ETL, SQL, Informatica",
  postedBy: recruiterId,
},
{
  title: "BI Engineer",
  companyName: "EY",
  description: "Develop business intelligence reports and dashboards.",
  location: "Kolkata",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "Power BI, SQL",
  postedBy: recruiterId,
},
{
  title: "CRM Consultant",
  companyName: "Salesforce",
  description: "Implement CRM solutions and customize workflows.",
  location: "Gurgaon",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "Salesforce CRM, Apex",
  postedBy: recruiterId,
},
{
  title: "SAP Consultant",
  companyName: "Accenture",
  description: "Implement SAP modules for enterprise clients.",
  location: "Hyderabad",
  salary: "₹15 LPA",
  jobType: "Full Time",
  skilledRequired: "SAP, ERP",
  postedBy: recruiterId,
},
{
  title: "Performance Test Engineer",
  companyName: "Capgemini",
  description: "Perform load and stress testing for enterprise applications.",
  location: "Chennai",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "JMeter, LoadRunner",
  postedBy: recruiterId,
},
{
  title: "Accessibility Engineer",
  companyName: "Atlassian",
  description: "Ensure applications meet accessibility standards.",
  location: "Remote",
  salary: "₹14 LPA",
  jobType: "Remote",
  skilledRequired: "WCAG, HTML, ARIA",
  postedBy: recruiterId,
},{
  title: "Frontend Developer",
  companyName: "Google",
  description: "Build modern React applications, collaborate with UI/UX teams, optimize web performance, and develop reusable frontend components for scalable products.",
  location: "Bangalore",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "React, JavaScript, HTML, CSS",
  postedBy: recruiterId,
},
{
  title: "Frontend Developer",
  companyName: "Microsoft",
  description: "Develop responsive web applications, integrate REST APIs, improve accessibility, and maintain high-quality frontend code.",
  location: "Hyderabad",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "React, TypeScript, CSS",
  postedBy: recruiterId,
},
{
  title: "Frontend Developer",
  companyName: "Amazon",
  description: "Create reusable UI components, optimize application speed, collaborate with backend developers, and ensure cross-browser compatibility.",
  location: "Pune",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Redux, JavaScript",
  postedBy: recruiterId,
},
{
  title: "Frontend Developer",
  companyName: "Adobe",
  description: "Develop interactive user interfaces using React and modern JavaScript while ensuring responsive design.",
  location: "Noida",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "React, HTML, CSS",
  postedBy: recruiterId,
},
{
  title: "Frontend Developer",
  companyName: "TCS",
  description: "Work on enterprise web applications, improve UI performance, and collaborate with cross-functional teams.",
  location: "Chennai",
  salary: "₹7 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Bootstrap, Git",
  postedBy: recruiterId,
},
{
  title: "Frontend Developer",
  companyName: "Infosys",
  description: "Build scalable frontend applications using React and JavaScript while maintaining coding standards.",
  location: "Mysore",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "React, JavaScript",
  postedBy: recruiterId,
},
{
  title: "Frontend Developer",
  companyName: "Wipro",
  description: "Develop responsive dashboards, integrate APIs, and improve application usability.",
  location: "Hyderabad",
  salary: "₹8.5 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Axios, CSS",
  postedBy: recruiterId,
},
{
  title: "Frontend Developer",
  companyName: "Capgemini",
  description: "Create reusable components, optimize UI rendering, and work closely with designers.",
  location: "Mumbai",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "React, SCSS, Git",
  postedBy: recruiterId,
},
{
  title: "Frontend Developer",
  companyName: "Accenture",
  description: "Develop enterprise frontend applications and deliver responsive user experiences.",
  location: "Gurgaon",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "React, TypeScript",
  postedBy: recruiterId,
},
{
  title: "Frontend Developer",
  companyName: "Cognizant",
  description: "Build high-quality web interfaces and collaborate with backend developers to integrate APIs.",
  location: "Kolkata",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "React, HTML, CSS",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "Google",
  description: "Develop scalable backend APIs, optimize database queries, and maintain secure server-side applications.",
  location: "Bangalore",
  salary: "₹13 LPA",
  jobType: "Full Time",
  skilledRequired: "Node.js, Express, MongoDB",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "Microsoft",
  description: "Design RESTful APIs, implement authentication, and optimize backend performance.",
  location: "Hyderabad",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "Node.js, Express, JWT",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "Amazon",
  description: "Build secure backend systems, work with databases, and improve API response times.",
  location: "Pune",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "Node.js, MongoDB",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "TCS",
  description: "Develop backend services and integrate enterprise applications using Node.js.",
  location: "Chennai",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "Express, MongoDB",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "Infosys",
  description: "Create scalable APIs, maintain backend systems, and ensure application security.",
  location: "Mysore",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "Node.js, REST API",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "Wipro",
  description: "Develop backend modules, optimize MongoDB queries, and support cloud deployment.",
  location: "Hyderabad",
  salary: "₹9.5 LPA",
  jobType: "Full Time",
  skilledRequired: "Express, MongoDB",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "Adobe",
  description: "Develop scalable backend architecture and secure authentication systems.",
  location: "Noida",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "Node.js, JWT",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "Capgemini",
  description: "Maintain backend APIs and integrate third-party services into enterprise applications.",
  location: "Mumbai",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "Express.js, MongoDB",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "Accenture",
  description: "Develop scalable microservices and backend APIs for enterprise products.",
  location: "Gurgaon",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "Node.js, Docker",
  postedBy: recruiterId,
},
{
  title: "Backend Developer",
  companyName: "Cognizant",
  description: "Design secure backend applications, optimize APIs, and maintain database integrity.",
  location: "Kolkata",
  salary: "₹8.5 LPA",
  jobType: "Full Time",
  skilledRequired: "Express, MongoDB",
  postedBy: recruiterId,
},
{
  title: "React Developer",
  companyName: "Google",
  description: "Develop advanced React applications with reusable components and API integration.",
  location: "Bangalore",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Redux",
  postedBy: recruiterId,
},
{
  title: "React Developer",
  companyName: "Microsoft",
  description: "Create interactive web applications using React and modern frontend practices.",
  location: "Hyderabad",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "React, JavaScript",
  postedBy: recruiterId,
},
{
  title: "React Developer",
  companyName: "Amazon",
  description: "Develop scalable frontend modules and optimize rendering performance.",
  location: "Pune",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Redux, HTML",
  postedBy: recruiterId,
},
{
  title: "React Developer",
  companyName: "Adobe",
  description: "Build reusable UI components and integrate REST APIs into web applications.",
  location: "Noida",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "React, CSS",
  postedBy: recruiterId,
},
{
  title: "React Developer",
  companyName: "TCS",
  description: "Work on enterprise React projects, fix bugs, and enhance application performance.",
  location: "Chennai",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Git",
  postedBy: recruiterId,
},{
  title: "React Developer",
  companyName: "Infosys",
  description: "Develop modern React applications, build reusable UI components, integrate REST APIs, and optimize application performance.",
  location: "Mysore",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Redux, JavaScript",
  postedBy: recruiterId,
},
{
  title: "React Developer",
  companyName: "Wipro",
  description: "Build responsive web applications using React and collaborate with backend developers to deliver scalable products.",
  location: "Hyderabad",
  salary: "₹9.5 LPA",
  jobType: "Full Time",
  skilledRequired: "React, HTML, CSS",
  postedBy: recruiterId,
},
{
  title: "React Developer",
  companyName: "Capgemini",
  description: "Develop reusable React components, optimize UI performance, and maintain frontend architecture.",
  location: "Mumbai",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "React, TypeScript",
  postedBy: recruiterId,
},
{
  title: "React Developer",
  companyName: "Accenture",
  description: "Create enterprise-grade React applications with clean code and modern UI practices.",
  location: "Gurgaon",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Redux Toolkit",
  postedBy: recruiterId,
},
{
  title: "React Developer",
  companyName: "Cognizant",
  description: "Design responsive interfaces and integrate APIs while ensuring excellent user experience.",
  location: "Kolkata",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Axios",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "Google",
  description: "Develop complete MERN stack applications, build REST APIs, and create responsive frontend interfaces.",
  location: "Bangalore",
  salary: "₹15 LPA",
  jobType: "Full Time",
  skilledRequired: "MongoDB, Express, React, Node.js",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "Microsoft",
  description: "Build scalable full-stack web applications using React and Node.js with cloud integration.",
  location: "Hyderabad",
  salary: "₹14 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Node.js, MongoDB",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "Amazon",
  description: "Work across frontend and backend technologies to deliver high-performance applications.",
  location: "Pune",
  salary: "₹13 LPA",
  jobType: "Full Time",
  skilledRequired: "MERN Stack",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "Adobe",
  description: "Develop enterprise applications, optimize APIs, and improve frontend performance.",
  location: "Noida",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Express, MongoDB",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "TCS",
  description: "Build scalable business applications using the MERN stack and REST APIs.",
  location: "Chennai",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "MongoDB, Node.js",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "Infosys",
  description: "Develop and maintain full-stack applications with modern JavaScript technologies.",
  location: "Mysore",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Node.js",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "Wipro",
  description: "Develop complete web applications and collaborate with UI/UX and QA teams.",
  location: "Hyderabad",
  salary: "₹10.5 LPA",
  jobType: "Full Time",
  skilledRequired: "Express, React",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "Capgemini",
  description: "Create responsive web applications with secure backend services.",
  location: "Mumbai",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "React, MongoDB",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "Accenture",
  description: "Develop enterprise software solutions using modern full-stack technologies.",
  location: "Gurgaon",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "MERN Stack",
  postedBy: recruiterId,
},
{
  title: "Full Stack Developer",
  companyName: "Cognizant",
  description: "Develop scalable web applications with responsive UI and optimized backend APIs.",
  location: "Kolkata",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "React, Express",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "Google",
  description: "Develop enterprise Java applications using Spring Boot and microservices.",
  location: "Bangalore",
  salary: "₹13 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, Spring Boot",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "Microsoft",
  description: "Build scalable Java backend services with REST APIs and cloud integration.",
  location: "Hyderabad",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, REST API",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "Amazon",
  description: "Develop backend systems using Java and optimize application performance.",
  location: "Pune",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, Spring",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "TCS",
  description: "Maintain enterprise Java applications and participate in code reviews.",
  location: "Chennai",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, MySQL",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "Infosys",
  description: "Develop secure Java applications with optimized database operations.",
  location: "Mysore",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, SQL",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "Wipro",
  description: "Build enterprise Java solutions using Spring Boot and Hibernate.",
  location: "Hyderabad",
  salary: "₹9.5 LPA",
  jobType: "Full Time",
  skilledRequired: "Spring Boot, Hibernate",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "Capgemini",
  description: "Design and develop Java-based web applications for enterprise clients.",
  location: "Mumbai",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, Maven",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "Accenture",
  description: "Develop enterprise backend applications and integrate cloud services.",
  location: "Gurgaon",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, Spring Boot",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "Cognizant",
  description: "Build robust Java applications and optimize backend performance.",
  location: "Kolkata",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, REST APIs",
  postedBy: recruiterId,
},
{
  title: "Java Developer",
  companyName: "IBM",
  description: "Develop enterprise-grade Java solutions using Spring Boot and microservices architecture.",
  location: "Bangalore",
  salary: "₹12 LPA",
  jobType: "Full Time",
  skilledRequired: "Java, Spring Boot, Microservices",
  postedBy: recruiterId,
},
{
  title: "Firmware Engineer",
  companyName: "Intel",
  description: "Develop low-level firmware for hardware devices, perform debugging, and optimize embedded systems.",
  location: "Bangalore",
  salary: "₹13 LPA",
  jobType: "Full Time",
  skilledRequired: "C, C++, Embedded C",
  postedBy: recruiterId,
},
{
  title: "IoT Developer",
  companyName: "Bosch",
  description: "Develop IoT applications, integrate smart devices, and build cloud-connected embedded solutions.",
  location: "Coimbatore",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "IoT, MQTT, Node.js",
  postedBy: recruiterId,
},
{
  title: "Scrum Master",
  companyName: "Persistent Systems",
  description: "Lead Agile teams, conduct sprint planning, remove blockers, and ensure successful project delivery.",
  location: "Nagpur",
  salary: "₹14 LPA",
  jobType: "Full Time",
  skilledRequired: "Scrum, Agile, Jira",
  postedBy: recruiterId,
},
{
  title: "IT Project Coordinator",
  companyName: "Hexaware",
  description: "Coordinate software projects, track timelines, prepare reports, and communicate with stakeholders.",
  location: "Chennai",
  salary: "₹8 LPA",
  jobType: "Full Time",
  skilledRequired: "Project Management, Excel",
  postedBy: recruiterId,
},
{
  title: "Technical Consultant",
  companyName: "Deloitte",
  description: "Provide technical consulting, gather requirements, implement solutions, and support enterprise clients.",
  location: "Hyderabad",
  salary: "₹11 LPA",
  jobType: "Full Time",
  skilledRequired: "SQL, Java, Communication",
  postedBy: recruiterId,
},
{
  title: "Linux Administrator",
  companyName: "Red Hat",
  description: "Maintain Linux servers, automate system tasks, monitor performance, and resolve infrastructure issues.",
  location: "Pune",
  salary: "₹10 LPA",
  jobType: "Full Time",
  skilledRequired: "Linux, Shell Scripting",
  postedBy: recruiterId,
},
{
  title: "CRM Developer",
  companyName: "Zoho",
  description: "Develop CRM modules, customize workflows, integrate APIs, and improve customer management systems.",
  location: "Chennai",
  salary: "₹9 LPA",
  jobType: "Full Time",
  skilledRequired: "CRM, JavaScript, APIs",
  postedBy: recruiterId,
},
];

async function seedJobs() {
  try {
    await mongoose.connect(DB_PATH);
    console.log("MongoDB Connected");

    // Remove this line if you don't want to delete existing jobs
    // await Job.deleteMany();

    await Job.insertMany(jobs);

    console.log("✅ Dummy jobs inserted successfully!");
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seedJobs();